# Generated by Django 3.2.15 on 2022-08-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.SlugField(blank=True),
        ),
    ]
