# Generated by Django 3.2.15 on 2022-08-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220823_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
