# Generated by Django 2.2.16 on 2022-08-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220828_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre_title',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='genre_title',
            old_name='title',
            new_name='title_id',
        ),
    ]
