# Generated by Django 2.2.16 on 2022-08-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220828_2039'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genre_title',
            name='unique_combination',
        ),
        migrations.RenameField(
            model_name='genre_title',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='genre_title',
            old_name='title_id',
            new_name='title',
        ),
        migrations.AddConstraint(
            model_name='genre_title',
            constraint=models.UniqueConstraint(fields=('title', 'genre'), name='unique_combination'),
        ),
    ]
