# Generated by Django 2.2.16 on 2022-08-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220828_2046'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genre_title',
            name='unique_combination',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique review',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='review_id',
        ),
        migrations.RenameField(
            model_name='genre_title',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='genre_title',
            old_name='title',
            new_name='title_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='title_id',
        ),
        migrations.AddConstraint(
            model_name='genre_title',
            constraint=models.UniqueConstraint(fields=('title_id', 'genre_id'), name='unique_combination'),
        ),
    ]
